name: Keep Alive

on:
  schedule:
    - cron: "*/5 * * * *"  # 매 5분마다 실행

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Keep Render alive
        run: curl -s https://fastapi-client-clean.onrender.com/
